project_id = "qtdxzgeeomgukkxfkwmh"

[functions.pesapal-callback]
verify_jwt = false

[functions.pesapal-initiate]
verify_jwt = false

[functions.select-competition-winners]
verify_jwt = false

[functions.analyze-submission]
verify_jwt = false

[functions.artist-analytics]
verify_jwt = false

[functions.trend-forecast]
verify_jwt = false

[functions.release-timing]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false
