project_id = "qtdxzgeeomgukkxfkwmh"

[functions.send-tip]
verify_jwt = true

[functions.select-competition-winners]
verify_jwt = false

[functions.analyze-submission]
verify_jwt = false

[functions.artist-analytics]
verify_jwt = false

[functions.trend-forecast]
verify_jwt = false

[functions.release-timing]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.recommend-tracks]
verify_jwt = false

[functions.classify-genre]
verify_jwt = false

[functions.detect-fraud]
verify_jwt = true

[functions.mpesa-deposit]
verify_jwt = false

[functions.mpesa-withdraw]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = true

[functions.ai-judge-submission]
verify_jwt = false

[functions.pesapal-initiate]
verify_jwt = true

[functions.pesapal-callback]
verify_jwt = false

[functions.pesapal-verify]
verify_jwt = true

[functions.progress-competition-stage]
verify_jwt = false

[functions.award-fan-badges]
verify_jwt = false

[functions.verify-activation-code]
verify_jwt = true

[functions.resend-activation-code]
verify_jwt = true

[functions.selar-initiate]
verify_jwt = true

[functions.selar-callback]
verify_jwt = false

[functions.selar-verify]
verify_jwt = true
